version: "3"

services:
  mysqlDB:
    container_name: spring-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db_example
    ports:
      - "3306:3306"