version: "3"

services:

  spring:
    container_name: spring-app
    image: spring-demo              # Change Name ?
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_HOSTNAME: mysqlDB
    ports:
      - "8080:8080"
    depends_on:
      - mysqlDB

  mysqlDB:
    container_name: spring-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db_example
    ports:
      - "3306:3306"