apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-demo
  labels:
    app: spring-app-demo
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app-demo
  template:
    metadata:
      labels:
        app: spring-app-demo
    spec:
      containers:
        - name: spring-app-demo
          image: manguilar22/spring:kube
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-app-demo-svc
spec:
  type: NodePort
  selector:
    app: spring-app-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31000