apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mysql-deploy
  labels:
    app: spring-mysql
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-mysql
  template:
    metadata:
      labels:
        app: spring-mysql
    spec:
      containers:
        - name: spring-mysql-deploy
          image: mysql:5.7
          ports:
            - name: mysql-port
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_USER
              value: mysqluser
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: db_example
---
apiVersion: v1
kind: Service
metadata:
  name: spring-mysql-deploy
spec:
  selector:
    app: spring-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
